# Generated by Django 3.0.2 on 2020-01-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasting_unit', models.CharField(max_length=255)),
                ('intercept', models.IntegerField()),
                ('slope', models.IntegerField()),
                ('loss', models.IntegerField()),
            ],
        ),
    ]
