# Generated by Django 3.0.2 on 2020-01-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample1',
            new_name='Forecast',
        ),
    ]
