# Generated by Django 3.0.2 on 2020-01-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0002_auto_20200130_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='dataset_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='intercept',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='slope',
            field=models.FloatField(),
        ),
    ]
