# Generated by Django 3.0.2 on 2020-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0003_auto_20200130_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasting_unit', models.CharField(max_length=255)),
                ('time_period', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
    ]
