# Generated by Django 3.0.2 on 2020-02-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0005_data_dataset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=54)),
                ('member_code', models.CharField(max_length=54)),
                ('member_description', models.CharField(max_length=50)),
                ('status', models.CharField(default='UP', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_id', models.CharField(max_length=54)),
                ('parent_level_id', models.CharField(max_length=54)),
                ('parent_code', models.CharField(max_length=54)),
                ('child_level_id', models.CharField(max_length=54)),
                ('child_code', models.CharField(max_length=54)),
            ],
        ),
    ]
