# Generated by Django 3.0.2 on 2020-02-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0007_geo_sku_sku_history_units_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku_history_units',
            old_name='member_code',
            new_name='geo_code',
        ),
        migrations.AddField(
            model_name='sku_history_units',
            name='time_code',
            field=models.CharField(default='j', max_length=54),
            preserve_default=False,
        ),
    ]
